[package]
name = "open-transaction-pool"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
ckb-async-runtime = "0.105"
ckb-crypto = "0.105"
ckb-hash = "0.105"
ckb-jsonrpc-types = "0.105"
ckb-sdk = { git = "https://github.com/EthanYuan/ckb-sdk-rust.git", branch = "opentx_sign_tx_ethan"}
ckb-types = "0.105"
ctrlc = "3.2.3"
dashmap = "5.4.0"
env_logger = "0.9.3"
log = "0.4.17"
jsonrpc-core = "18.0"
jsonrpc-http-server = "18.0"
jsonrpc-server-utils = "18.0"
secp256k1 = { version = "0.24", features = ["recovery"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process", "sync"] }

otx-format = { path = "./otx-format" }
otx-plugin-protocol = { path = "otx-plugin-protocol" }
otx-pool = { path = "./otx-pool" }
utils = { path = "./utils" }

[workspace]
members = [
    "otx-format",
    "otx-plugin-protocol",
    "otx-pool",
    "utils",

]
