pub use crate::generated::packed;
use crate::jsonrpc_types::OpenTransaction;

use ckb_jsonrpc_types::{Deserialize, Script, Serialize};
use ckb_types::H256;

use std::collections::HashMap;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum OpenTxStatus {
    /// Status "pending". The open transaction is in the pool, and not proposed yet.
    Pending,
    /// Status "merged". The open transaction is generated by merging multiple open transactions and is still unsigned.
    Merged(H256),
    /// Status "committed". The open transaction has been committed to the canonical chain.
    Committed(H256),
    // Status "rejected". The open transaction has been recently removed from the pool.
    /// Due to storage limitations, the pool can only hold the most recently removed transactions.
    Rejected(String),
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct OpenTxWithStatus {
    pub otx: OpenTransaction,
    pub status: OpenTxStatus,
}

impl OpenTxWithStatus {
    pub fn new(otx: OpenTransaction) -> Self {
        OpenTxWithStatus {
            otx,
            status: OpenTxStatus::Pending,
        }
    }
}

#[derive(Debug)]
pub struct PaymentAmount {
    pub capacity: i128,
    pub fee: u64,
    pub x_udt_amount: HashMap<Script, i128>,
    pub s_udt_amount: HashMap<Script, i128>,
}

#[cfg(test)]
mod test {
    use crate::types::packed::OpenTransaction;

    use super::*;
    use ckb_jsonrpc_types::JsonBytes;
    use molecule::prelude::*;
    use packed::OpenTransactionBuilder;

    #[test]
    fn test_serialize() {
        let builder = OpenTransactionBuilder::default();
        let opentx = builder.build();
        let opentx_bytes = opentx.as_bytes();
        let json_rpc_format = JsonBytes::from_bytes(opentx_bytes);
        println!("{:?}", opentx);
        println!("{:?}", json_rpc_format);

        let opentx_bytes = json_rpc_format.as_bytes();
        println!("{:?}", opentx_bytes);
        let opentx_rebuild = OpenTransaction::from_slice(opentx_bytes).unwrap();

        assert_eq!(opentx.as_bytes(), opentx_rebuild.as_bytes());
    }
}
