# The network type reference https://github.com/nervosnetwork/ckb-cli/blob/master/ckb-sdk/src/constants.rs
[network_config]
listen_uri = "http://127.0.0.1:8118"


[built_in_plugin_dust_collector]
enabled = true
key = "PRIVKEY"
default_address = "DEFAUT_ADDRESS"


[built_in_plugin_atomic_swap]
enabled = true


[built_in_plugin_signer]
enabled = true
key = "PRIVKEY"
default_address = "DEFAUT_ADDRESS"


[ckb_config]
network_type = "ckb"
ckb_uri = "http://127.0.0.1:8114"


[[scripts]]
script_name = "secp256k1_blake160"
script = '''
{
    "args": "0x",
    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x9c6cff38bf3dbfe28d57035973f0dd1ab60bddac46549e5fc50d2a46e7c0c5f5"
    }
}
'''


[[scripts]]
script_name = "dao"
script = '''
{
    "args": "0x",
    "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x2",
        "tx_hash": "0x8592d17f7d574cf51b744d66fe9e14a09b915ecaf7ff40450d270c8b2a7a1372"
    }
}
'''


[[scripts]]
script_name = "sudt"
script = '''
{
    "args": "0x",
    "code_hash": "0x9c6933d977360f115a3e9cd5a2e0e475853681b80d775d93ad0f8969da343e56",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x7",
        "tx_hash": "0x8592d17f7d574cf51b744d66fe9e14a09b915ecaf7ff40450d270c8b2a7a1372"
    }
}
'''


[[scripts]]
script_name = "anyone_can_pay"
script = '''
{
    "args": "0x",
    "code_hash": "0x6283a479a3cf5d4276cd93594de9f1827ab9b55c7b05b3d28e4c2e0a696cfefd",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x2",
        "tx_hash": "0x9c6cff38bf3dbfe28d57035973f0dd1ab60bddac46549e5fc50d2a46e7c0c5f5"
    }
}
'''


[[scripts]]
script_name = "cheque"
script = '''
{
    "args": "0x",
    "code_hash": "0x1a1e4fef34f5982906f745b048fe7b1089647e82346074e0f32c2ece26cf6b1e",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "dep_group",
    "out_point": {
        "index": "0x3",
        "tx_hash": "0x9c6cff38bf3dbfe28d57035973f0dd1ab60bddac46549e5fc50d2a46e7c0c5f5"
    }
}
'''


[[scripts]]
script_name = "pw_lock"
script = '''
{
    "args": "0x",
    "code_hash": "0xe09352af0066f3162287763ce4ddba9af6bfaeab198dc7ab37f8c71c9e68bb5b",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x8",
        "tx_hash": "0x8592d17f7d574cf51b744d66fe9e14a09b915ecaf7ff40450d270c8b2a7a1372"
    }
}
'''

[[scripts]]
script_name = "omni_lock"
script = '''
{
    "args": "0x",
    "code_hash": "0xbb4469004225b39e983929db71fe2253cba1d49a76223e9e1d212cdca1f79f28",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x9",
        "tx_hash": "0x8592d17f7d574cf51b744d66fe9e14a09b915ecaf7ff40450d270c8b2a7a1372"
    }
}
'''

[[scripts]]
script_name = "xudt_rce"
script = '''
{
    "args": "0x",
    "code_hash": "0x73e5467341b55ffd7bdeb5b6f32aa0e9433baf6808f8c5f2472dbc36b1ab04f7",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0xa",
        "tx_hash": "0x8592d17f7d574cf51b744d66fe9e14a09b915ecaf7ff40450d270c8b2a7a1372"
    }
}
'''
